#include "TFile.h"
#include "TH1F.h"
#include <iostream>
#include <fstream>
using namespace std;

void analysis() {
    Int_t nbins = 800;
	TFile f("/home/marko/H4Analysis/ntuples/analysis_4443.root"); //ntuple generated by H4Analysis tool
	TFile f1("/home/marko/H4Analysis/ntuples/analysis_3905.root");
    TCanvas* TimeandFreq = new TCanvas("TimeandFreq","Time and Frequency",1500,900);
    TCanvas* Freq = new TCanvas("Freq","Frequency",800,1200);
    TCanvas* TimeSignal = new TCanvas("TimeSignal","Pure Signal",800,1200);
	TimeandFreq->Divide(2,2);
	TTree* h4 = (TTree*) f.Get("h4");
    TTree* h4_2 = (TTree*) f1.Get("h4");
    TTree* reco = (TTree*) f1.Get("reco");
    TTree* wf = (TTree*) f1.Get("wf");
    Int_t WF_ch[13312];
    Int_t APD1;
    Int_t APD2;
    Int_t APD3;
    Int_t APD4;
    Int_t APD5;
    Int_t APD6;
    Int_t SiPM1;
    Int_t SiPM2;
    Float_t amp_max[13];
    Float_t b_rms[13];
    Float_t charge_tot[13];
    TBranch *b_WF_ch;
    TBranch *b_APD1;
    TBranch *b_APD2;
    TBranch *b_APD3;
    TBranch *b_APD4;
    TBranch *b_APD5;
    TBranch *b_APD6;
    TBranch *b_SiPM1;
    TBranch *b_SiPM2;
    TBranch *b_amp_max;
    TBranch *b_charge_tot;
    TBranch *b_b_rms;
    wf->SetBranchAddress("WF_ch", &WF_ch, &b_WF_ch);
    reco->SetBranchAddress("APD1", &APD1, &b_APD1);
    reco->SetBranchAddress("APD2", &APD2, &b_APD2);
    reco->SetBranchAddress("APD3", &APD3, &b_APD3);
    reco->SetBranchAddress("APD4", &APD4, &b_APD4);
    reco->SetBranchAddress("APD5", &APD5, &b_APD5);
    reco->SetBranchAddress("APD6", &APD6, &b_APD6);
    reco->SetBranchAddress("SiPM1", &SiPM1, &b_SiPM1);
    reco->SetBranchAddress("SiPM2", &SiPM2, &b_SiPM2);
    reco->SetBranchAddress("amp_max", &amp_max, &b_amp_max);
    reco->SetBranchAddress("charge_tot", &charge_tot, &b_charge_tot);
    reco->SetBranchAddress("b_rms", &b_rms, &b_b_rms);
	TH2F* WavePulse = new TH2F ("WavePulse", "Wave Pulse", nbins, -0.1, 159.9, 850, -50, 800);
    TH2F* NoisePulse = new TH2F ("NoisePulse", "Noise", nbins, -0.1, 159.9, 100, -50, 50);
    TH1F* PulseTime = new TH1F ("PulseTime", "Original Wave Pulse", nbins, -0.1, 159.9); //nanoseconds
	h4->Draw("WF_val:WF_time>>WavePulse", "WF_ch==2 && event==1 && spill==1");
    h4_2->Draw("WF_val:WF_time>>NoisePulse","WF_ch==APD1 && amp_max[APD3]<25 && b_rms[APD3]<5. && charge_tot[APD3]<20000 &&  amp_max[APD5]<25 && b_rms[APD5]<5. &&  amp_max[APD6]<25 && b_rms[APD6]<5. &&  amp_max[APD4]<25 && b_rms[APD4]<5. && amp_max[SiPM1]<20 && amp_max[SiPM2]<20 && amp_max[APD1]<40 && amp_max[APD2]<40 && b_rms[APD1]<5. && b_rms[APD2]<5.");
    for (Int_t i=0; i<nbins; i++) {
		for (Int_t j=0; j<4096; j++) {
			if (WavePulse->GetBinContent(i+1, j) != 0) {
				PulseTime->SetBinContent(i+1,j-50);
			}
		}
	}
    TH1F *NoiseTime = new TH1F ("NoiseTime", "Noise", nbins, -0.1, 159.9);
    for (Int_t i=0; i<nbins; i++) {
        for (Int_t j=0; j<4096; j++) {
            if (NoisePulse->GetBinContent(i+1, j) != 0) {
                NoiseTime->SetBinContent(i+1,j-62.9087);
            }
        }
    }
    for (Int_t i=0;i<13312;i++) {
        if (WF_ch[i]==APD1 && amp_max[APD3]<25 && b_rms[APD3]<5. && charge_tot[APD3]<20000 &&  amp_max[APD5]<25 && b_rms[APD5]<5. &&  amp_max[APD6]<25 && b_rms[APD6]<5. &&  amp_max[APD4]<25 && b_rms[APD4]<5. && amp_max[SiPM1]<20 && amp_max[SiPM2]<20 && amp_max[APD1]<40 && amp_max[APD2]<40 && b_rms[APD1]<5. && b_rms[APD2]<5.) {
            
        }
    //if (WF_ch==APD1 && amp_max[APD3]<25 && b_rms[APD3]<5. && charge_tot[APD3]<20000 &&  amp_max[APD5]<25 && b_rms[APD5]<5. &&  amp_max[APD6]<25 && b_rms[APD6]<5. &&  amp_max[APD4]<25 && b_rms[APD4]<5. && amp_max[SiPM1]<20 && amp_max[SiPM2]<20 && amp_max[APD1]<40 && amp_max[APD2]<40 && b_rms[APD1]<5. && b_rms[APD2]<5.) {
    }
    //for (Int_t i=0; i<10000; i++){
    //    for (Int_t j=0;j<10000; j++) {
    //        
    //    }
    //}
	new TFile("/home/marko/H4Analysis/ntuples/analysis_4443.root"); // ignore this reloading of the same file, it is required or else the plots do not show up (try commenting it out)
    TimeandFreq->cd(1);
    PulseTime->GetXaxis()->SetTitle("Time (ns)");
    PulseTime->GetYaxis()->SetTitle("Amplitude");
    PulseTime->DrawClone(); //Wave Pulse in Time domain
    TimeandFreq->cd(2);
    TH1F* PulseFreq = new TH1F ("PulseFreq", "Pulse FFT", nbins, 0, 5);
    TH1F* PulsePhase = new TH1F ("PulsePhase", "Pulse Phase", nbins, -0.1, 799.9);
    PulseTime->FFT(PulseFreq, "MAG");
    PulseTime->FFT(PulsePhase, "PH");
    PulseFreq->SetLineColor(kRed);
    PulseFreq->GetXaxis()->SetTitle("Frequency (GHz)");
    PulseFreq->GetYaxis()->SetTitle("Amplitude");
    PulseFreq->DrawClone(); //Wave Pulse in Frequency domain
    gPad->SetLogy();
    TimeandFreq->cd(3);
    NoiseTime->GetXaxis()->SetTitle("Time (ns)");
    NoiseTime->GetYaxis()->SetTitle("Amplitude");
    NoiseTime->DrawClone(); // Noise from pedestal in Time domain
    TimeandFreq->cd(4);
    TH1F* NoiseFreq = new TH1F ("NoiseFreq", "Noise FFT", nbins, 0, 5);
    NoiseTime->FFT(NoiseFreq, "MAG");
    NoiseFreq->GetXaxis()->SetTitle("Frequency (GHz)");
    NoiseFreq->GetYaxis()->SetTitle("Amplitude");
    NoiseFreq->Draw(); // Noise from pedestal in Frequency domain
    gPad->SetLogy();
    Freq->Divide(1,3);
    Freq->cd(1);
    PulseFreq->DrawClone();
    gPad->SetLogy();
    Freq->cd(2);
    NoiseFreq->DrawClone();
    gPad->SetLogy();
    Freq->cd(3);
    PulseFreq->SetTitle("Pulse and Noise FFT Comparison");
    PulseFreq->Draw();
    NoiseFreq->Draw("same");
    gPad->SetLogy();
    TH1F* UnscaledSignalFreq = new TH1F ("UnscaledSignalFreq", "Unscaled Signal Frequency", nbins, -0.1, 799.9);
    for (Int_t l=0; l<nbins; l++) {
        UnscaledSignalFreq->SetBinContent(l+1, (PulseFreq->GetBinContent(l+1)-NoiseFreq->GetBinContent(l+1))/PulseFreq->GetBinContent(l+1));
    }
    TH1F* SignalFreq = new TH1F ("SignalFreq", "Signal Frequency", nbins, 0, 799.9);
    for (Int_t m=0; m<nbins; m++) {
        SignalFreq->SetBinContent(m+1, UnscaledSignalFreq->GetBinContent(m+1)*PulseFreq->GetBinContent(m+1));
    }
    Double_t *re_full = new Double_t[nbins];
    Double_t *im_full = new Double_t[nbins];
    for (Int_t n=0; n<nbins; n++) {
        (re_full)[n]=(SignalFreq->GetBinContent(n+1)*cos(PulsePhase->GetBinContent(n+1)));
        (im_full)[n]=(SignalFreq->GetBinContent(n+1)*sin(PulsePhase->GetBinContent(n+1)));
    }
    TVirtualFFT *invFFT = TVirtualFFT::FFT(1, &nbins, "C2R M K");
    invFFT->SetPointsComplex(re_full, im_full);
    invFFT->Transform();
    TH1 *Signal = 0;
    Signal = TH1::TransformHisto(invFFT,Signal,"Re");
    Signal->SetTitle("Recovered Signal 'S'");
    TH1F* BetterSignal = new TH1F ("BetterSignal", "Recovered Signal", nbins, -0.1, 159.9);
    for (Int_t p=0; p<nbins; p++) {
        BetterSignal->SetBinContent(p+1, Signal->GetBinContent(p+1)/nbins);
    }
    TimeSignal->Divide(1,2);
    TimeSignal->cd(1);
    PulseTime->DrawClone(); //Original Wave Pulse
    TimeSignal->cd(2);
    BetterSignal->GetXaxis()->SetTitle("Time (ns)");
    BetterSignal->GetYaxis()->SetTitle("Amplitude");
    BetterSignal->SetLineColor(kRed);
    BetterSignal->Draw(); // Recovered Wave Pulse with decreased contribution from background noise
    PulseTime->DrawClone("same");
}


//for (Int_t k=0; k<PulseTime->GetNbinsX(); k++) {
//        NoiseTime->SetBinContent(k+1, PulseTime->GetBinContent((k+1)%250));
//}

//h4->Draw("WF_val:WF_time"," WF_ch==APD1 && amp_max[APD3]<25 && b_rms[APD3]<5. && charge_tot[APD3]<20000 &&  amp_max[APD5]<25 && b_rms[APD5]<5. &&  amp_max[APD6]<25 && b_rms[APD6]<5. &&  amp_max[APD4]<25 && b_rms[APD4]<5. && amp_max[SiPM1]<20 && amp_max[SiPM2]<20 && amp_max[APD1]<40 && amp_max[APD2]<40 && b_rms[APD1]<5. && b_rms[APD2]<5.");


//gPad->SetGrid();

// Double_t binCenter = xaxis->GetBinCenter(bin); //where bin is a number corresponding to a bin
// Int_t BinSize = htemp->GetNBins();
// TAxis *xaxis = htemp->GetXaxis();
// TAxis *yaxis = htemp->GetYaxis();

//NoiseTime->GetXaxis()()->SetRangeUser(10,990);

//Freq->cd(4);
//UnscaledSignalFreq->DrawClone();

//NoiseTime->SetBinContent(k+1, sin(k/10.)/10.);


// TH2F* WavePulse=(TH2F*)gDirectory->Get("htemp");

// TTree *MyTree = new TTree("MyTree", "MyTree");
// MyTree->ReadFile("storage.txt", "x:y");
// MyTree->Draw("y:x","");
// TimeandFreq->cd(1);
// WavePulse->DrawClone("colz");
//NoiseTime->SetTitle("FFT");

//Double_t PulseFreqIntegral = PulseFreq->Integral();
//Double_t NoiseFreqIntegral = NoiseFreq->Integral();
//PulseFreq->Scale(1/PulseFreqIntegral);
//NoiseFreq->Scale(1/NoiseFreqIntegral);

//ofstream myfile;

//myfile.open ("storage.txt");

//myfile << "x" << "\t \t" << "y" << endl;

            //myfile << i << "\t \t" << j-50 << endl; //subtract j by distance from lower limit of y to 0 (if negative)

//myfile.close();

//TGraph *MyGraph = new TGraph("storage.txt");
